# Parameters for compiling

ARDUINO_DIR     = /usr/share/arduino/
TARGET          = output
ARDUINO_LIBS    = IntSynthLib Wire TimerOne SPI DueMcpDac


# Avrdude code for programming

BOARD_TAG               = uno 
ARDUINO_PORT            = /dev/ttyACM0
AVRDUDE_ARD_PROGRAMMER  = arduino
AVRDUDE_ARD_BAUDRATE    = 115200

# Arduino makefile
include $(ARDUINO_DIR)/Arduino.mk
